### ISSUE TITLE
Windows 10.14393.576停止运行

### ISSUE THREAD

**Issue by Riajyuu** [Robotxm/mWiFi#1]
启动时立刻停止运行，已确认安装NET Framework 4

**Comment by Robotxm** [comment]
4年前写的小玩意竟然还有人回应，感动。
抛开这些，能详细提供下您的环境吗，以及如果在VS里编译运行的时候是否有强退？如果有，请提供下VS的log。
Windows 8.1/Windows 10上我测试时没有问题的。

**Comment by Riajyuu** [comment]
我使用的是你的个人网站上提供的二进制文件，没有安装VS套件

**Comment by Robotxm** [comment]
3.2(3.2.0.36)版本是吗

**Comment by Riajyuu** [comment]
是的 这个截图可能有所帮助
![20161219_103528](https://cloud.githubusercontent.com/assets/16912240/21299477/0582bb1e-c5d7-11e6-9d57-45d62d8f2559.png)

**Comment by Robotxm** [comment]
你加下我QQ：1017815010，这样更方便一点
